name: bazario
description: "A mobile application built for both customers and vendor owners/members of the NeighborGoods association. The app provides a seamless way for customers to discover events, explore vendors, and shop products, while enabling vendors to manage their participation, products, and required documents all in one place."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.0.2
  http: ^1.1.0
  flutter_svg: ^2.0.9
  iconify_flutter: ^0.0.7
  solar_icons: ^0.0.5
  iconify_design: ^1.0.1
  cloudinary_url_gen: ^1.8.0
  image_picker: ^1.2.0
  loading_animation_widget: ^1.3.0
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  file_picker: ^10.3.3
  url_launcher: ^6.3.2
  carousel_slider: ^5.1.1
  flutter_inset_shadow: ^2.0.3
  shimmer: ^3.0.0
  geolocator: ^13.0.0
  geocoding: ^3.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  shared_preferences: ^2.5.3
  tutorial_coach_mark: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/images/my-docs-list/
    - lib/assets/icons/
    - .env
  fonts:
    - family: Starla
      fonts:
        - asset: lib/assets/fonts/Starla.ttf
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
        - asset: lib/assets/fonts/Poppins-Bold.ttf
    - family: Bagel Fat One
      fonts:
        - asset: lib/assets/fonts/BagelFatOne-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/bazario-logo.png"
